### ISSUE TITLE
 'NoneType' object has no attribute 'tbody'

### ISSUE THREAD

**Issue by ngouy** [matejbasic/PythonScrapyBasicSetup#2]
From a fresh ubuntu install on my serv, after following all steps from the read.me file, I get the following error when I run 
`python run.py`

'NoneType' object has no attribute 'tbody'

**Comment by nimble0** [comment]
The proxy list that the proxy middleware uses, no longer exists. You have to find a new proxy list and adjust the code to read it in order to fix this.

**Comment by matejbasic** [comment]
@ngouy @nimble0 
HttpProxyMiddleware is updated with the new source! I highly recommend using the TorProxyMiddleware which is now set as default one in settings.py
