### ISSUE TITLE
TOR specified ExitNodes

### ISSUE THREAD

**Issue by wasiqnoorahmad** [matejbasic/PythonScrapyBasicSetup#3]
It would be great if we specify the TOR exit nodes to use. Can we add this use case?

**Comment by matejbasic** [comment]
@wasiqnoorahmad good feature. I've added this in https://github.com/matejbasic/PythonScrapyBasicSetup/commit/a257313125887cdc3380a11d087de1df2e788bd9 commit. Just uncomment EXIT_NODES in settings.py and define needed country codes.
