### ISSUE TITLE
Source path fix for "data/user_agents.xml"

### ISSUE THREAD

**Issue by ysmike** [matejbasic/PythonScrapyBasicSetup#4]
In the user_agent.py file (PythonScrapyBasicSetup/PythonScrapyBasicSetup/middlewares/user_agent.py), the source_path variable should point to "../data/user_agents.xml" instead of "data/user_agents.xml" to correctly reflect the tree structure. Small change but wanted to let you know.

**Comment by matejbasic** [comment]
@ysmike thank you but current working directory for `RandomUserAgentMiddleware` is project's root dir.
